export const ADD_VOTE = 'ADD_VOTE';
export const CHANGE_VIEW_DATA = 'CHANGE_VIEW_DATA';
export const UPDATE_FILTER_CANDIDATE = 'UPDATE_FILTER_CANDIDATE';
export const LOAD_CANDIDATES = 'LOAD_CANDIDATES';